version: '3.7'
services:
  vault:
    build: .
    hostname: "vault"
    restart: on-failure
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_LOG_LEVEL=debug
      - AWS_DEFAULT_REGION
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_TOKEN
    volumes:
      - ./backup:/vault
    ports:
      - 169.254.32.1:8200:8200
    cap_add:
      - IPC_LOCK
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.entrypoints=https"
      - "traefik.http.routers.vault.rule=HostRegexp(`vault.{domain:.+}`)"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
  vault-proxy:
    image: letfn/consul-envoy:v1.8.0-v1.14.2
    environment:
      CONSUL_HTTP_ADDR: 169.254.32.1:8500
      CONSUL_GRPC_ADDR: 169.254.32.1:8502
      SERVICE_CONFIG: /config/vault.hcl
      CENTRAL_CONFIG: /central_config/vault.hcl
    volumes:
      - "./etc/service_config:/config"
      - "./etc/central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "vault"]
    network_mode: "service:vault"

networks:
  default:
    external:
      name: kitt
